### PR TITLE
Document `async-tokio` feature on docs.rs

### PR DESCRIPTION
**Pull request by dfrankland**
Documents things behind features on docs.rs

Screen Shot 2021-01-11 at 5 51 44 PM
Screen Shot 2021-01-11 at 5 51 18 PM

### CODE REVIEW

**Review by ryankurte — APPROVED** [review]
thanks for the PR, lgtm! we just need to have a look into what's up with the CI build

**Comment by eldruin** [comment]
bors r=ryankurte

**Comment by ryankurte** [comment]
ahh another candidate for the github-actions conversion :-/

**Comment by eldruin** [comment]
Yes, but this one also failed to build on Rust 1.39.0 due to the `object` dependency:
```
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:114:1
    |
114 | #[non_exhaustive]
    | ^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/44109
error[E0658]: subslice patterns are unstable
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:162:41
    |
162 |             [0x7f, b'E', b'L', b'F', 1, ..] => FileKind::Elf32,
    |                                         ^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/62254
```
And also this:
```
/usr/bin/docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```
I have deactivated the tests on the MSRV on #47. Once that is merged, this could be rebased and we can try again.

**Comment by eldruin** [comment]
Alright now that the CI is working again, @dfrankland could you rebase this to the current master?

**Comment by eldruin** [comment]
Hmm maybe this is fine with the merge that bors does so let's try.

bors retry

**Comment by eldruin** [comment]
bors retry

**Comment by eldruin** [comment]
we are hitting the rate limit from docker.

bors retry
