### PR TITLE
Updated nix dependency version to 0.14

### PR DESCRIPTION
**Pull request by drinkdhmo**
This fixes the compilation error on a Raspberry Pi Zero W (and presumably other armhf7 devices).

### CODE REVIEW

**Comment by drinkdhmo** [comment]
Attempts to resolve #13.

**Comment by drinkdhmo** [comment]
`nix::poll::EventFlags` was renamed to `nix::poll::PollFlags` in upstream. See [this pull request](https://github.com/nix-rust/nix/pull/1024).

**Comment by posborne** [comment]
Hi @drinkdhmo, thanks for the change.  Would you mind confirming that this is working and clean up the branch to remove the merge commit.  Probably just squash all this down to a single commit.

P.S. Repo just moved to rust-embedded org.

**Comment by drinkdhmo** [comment]
Can confirm, this compiles and gpio works on a RPi zero W, with kernel `4.19.42+`.

**Comment by posborne** [comment]
Excellent, thanks @drinkdhmo.  Going to try bors but I think it isn't quite fully setup.
